### ISSUE TITLE
the weight of the application has increased 66 times. It is probably necessary to reduce memory consumption.

### ISSUE THREAD

**Issue by Wjxfi** [warren-bank/Android-WebMonkey#10]
the weight of the application has increased 66 times. It is probably necessary to reduce memory consumption.

![137ea38f-91ae-4d90-bec0-cec7e82bef49.jpg](https://github.com/warren-bank/Android-WebMonkey/assets/113500363/cd821cd9-7062-4166-a09e-de13b7be238f)

![6b692aa5-e730-461b-be73-a00392a75535.jpg](https://github.com/warren-bank/Android-WebMonkey/assets/113500363/e32836b1-7a89-4629-951a-b882c7809480)

**Comment by warren-bank** [comment]
unfortunately, I don't understand Russian.. but:
* the APK size for the [most recent release](https://github.com/warren-bank/Android-WebMonkey/releases/tag/v01.00.25) is (at most): 237 KB
* if you're referring to RAM usage, then..
  - disabling the "Ad Blocker" in settings will prevent the block list from being loaded into memory at runtime
  - any additional RAM usage is the result of the userscripts installed by the user

**Comment by warren-bank** [comment]
optionally.. there are variations of the APK in the releases that don't even include the "Ad Blocker" functionality

**Comment by warren-bank** [comment]
I refer to my earlier comment.

**Comment by warren-bank** [comment]
annecdotally, on the phone I'm using to test the app presently..
after clearing cache, `Settings > Storage` reports:
* app size: 247 kB
* user data: 312 kB
  - which is probably the one userscript that I'm currently testing..
* cache: 0 B
* total: 559 kB

this is:
* version 001.00.24-08API
* with: Ad Block
* with: all language translations

so..
my guess is that you have some userscripts installed,
which store a lot of data.

some do..
some of mine do..
and that's perfectly OK..
but it's not the app's fault..
if you don't like it, uninstall the heavy-weight userscript(s).

**Comment by warren-bank** [comment]
I just realized that I was running one version behind..
and installed [v1.0.25](https://github.com/warren-bank/Android-WebMonkey/releases/download/v01.00.25/WebMonkey-001.00.25-08API-withAllLanguageTranslations-withAdBlock-release.apk)

now.. settings reports:
* app size: 370 kB
* user data: 279 kB
  - which is probably the one userscript that I'm currently testing..
* cache: 0 B
* total: 649 kB

**Comment by warren-bank** [comment]
1. you just installed an english-only version.. which probably isn't what you want
2. shrug..
   * maybe your phone is attibuting data stored by your System WebView to this app?<br>..which wouldn't make any sense
     - it's a shared component used by many apps
     - that's the only other place "data" could be hiding

**Comment by warren-bank** [comment]
..maybe Putin has figured a way to use this app on your phone to bomb a hospital or set fire to an orphanage?
