### ISSUE TITLE
variable error in wrapper

### ISSUE THREAD

**Issue by luomoxu** [warren-bank/Android-WebMonkey#18]
I try run this userscript in tampermonkey(chrome 130,windows 10) and webMonkey(v04.08.00 webview 129,android 9)
The following is the result of running
webMonkey get some diff and error
```js
// ==UserScript==
// @name         debug
// @namespace    debug
// @version      0.0.1
// @description  debug
// @author       debug
// @match        https://*/*
// @grant        unsafeWindow
// ==/UserScript==
console.log(this);
console.log(window);
console.log(unsafeWindow);
console.log(globalThis);
console.log(self);


window.debug1 = "ok";
try {
    console.log("window.debug1", window.debug1);
    console.log("unsafeWindow.debug1",unsafeWindow.debug1);
    console.log("this.debug1", this.debug1);
    console.log("globalThis.debug1", globalThis.debug1);
    console.log("self.debug1", self.debug1);
    console.log("debug1", debug1);
} catch (error) {
    console.log(error);
}
var debug2 = "ok";
try {
    console.log("debug2", debug2);
    console.log("window.debug2", window.debug2);
    console.log("unsafeWindow.debug2",unsafeWindow.debug2);
    console.log("this.debug2", this.debug2);
    console.log("globalThis.debug2", globalThis.debug2);
    console.log("self.debug2", self.debug2);
} catch (error) {
    console.log(error);
}
unsafeWindow.debug3 = "ok";
try {
    console.log("debug3", debug3);
    console.log("window.debug3", window.debug3);
    console.log("unsafeWindow.debug3",unsafeWindow.debug3);
    console.log("this.debug3", this.debug3);
    console.log("globalThis.debug3", globalThis.debug3);
    console.log("self.debug3", self.debug3);
} catch (error) {
    console.log(error);
}

this.debug4 = "ok";
try {
    console.log("window.debug4", window.debug4);
    console.log("unsafeWindow.debug4",unsafeWindow.debug4);
    console.log("this.debug4", this.debug4);
    console.log("globalThis.debug4", globalThis.debug4);
    console.log("self.debug4", self.debug4);
    console.log("debug4", debug4);
} catch (error) {
    console.log(error);
}
globalThis.debug5 = "ok";
try {
    console.log("window.debug5", window.debug5);
    console.log("unsafeWindow.debug5",unsafeWindow.debug5);
    console.log("this.debug5", this.debug5);
    console.log("globalThis.debug5", globalThis.debug5);
    console.log("self.debug5", self.debug5);
    console.log("debug5", debug5);
} catch (error) {
    console.log(error);
}
self.debug6 = "ok";
try {
    console.log("window.debug6", window.debug6);
    console.log("unsafeWindow.debug6",unsafeWindow.debug6);
    console.log("this.debug6", this.debug6);
    console.log("globalThis.debug6", globalThis.debug6);
    console.log("self.debug6", self.debug6);
    console.log("debug6", debug6);
} catch (error) {
    console.log(error);
}

```
|                                  | debug     | window.debug  | unsafeWindow.debug | this.debug    | globalThis.debug | self.debug    |
| -------------------------------- | --------- | ------------- | ------------------ | ------------- | ---------------- | ------------- |
| tampermonkey  debug              | ok        | undefined     | undefined          | undefined     | undefined        | undefined     |
| WebMonkey debug                  | ok        | undefined     | undefined          | undefined     | undefined        | undefined     |
| tampermonkey  window.debug       | **ok**    | ok            | undefined          | ok            | ok               | ok            |
| WebMonkey window.debug           | **error** | ok            | undefined          | ok            | ok               | ok            |
| tampermonkey  unsafeWindow.debug | ok        | **undefined** | ok                 | **undefined** | **undefined**    | **undefined** |
| WebMonkey unsafeWindow.debug     | ok        | **ok**        | ok                 | **ok**        | **ok**           | **ok**        |
| tampermonkey  this.debug         | **ok**    | ok            | undefined          | ok            | ok               | ok            |
| WebMonkey this.debug             | **error** | ok            | undefined          | ok            | ok               | ok            |
| tampermonkey  globalThis.debug   | **ok**    | ok            | undefined          | ok            | ok               | ok            |
| WebMonkey globalThis.debug       | **error** | ok            | undefined          | ok            | ok               | ok            |
| tampermonkey  self.debug         | **ok**    | ok            | undefined          | ok            | ok               | ok            |
| WebMonkey self.debug             | **error** | ok            | undefined          | ok            | ok               | ok            |

**Comment by warren-bank** [comment]
Thanks for writing this test case and comparing the results between the two userscript managers.

I see 2 main differences in the results that you posted..

1. when a variable is added to `unsafeWindow` (ie: the _real_ `window` object)
   * _Tampermonkey_ cannot read this variable from the sandboxed `window` object
   * _WebMonkey_ can read this variable from the sandboxed `window` object
     - ..which is also aliased through all of the other variable names you tested: `self`, `this`, `globalThis`
     - this is the behavior for __all__ variables belonging to `unsafeWindow`:
       * the sandbox `window` can read these variables
       * off-hand, I would guess that it can also modify their values (if/when they're passed by reference)
       * but any new values added to the sandbox `window` only exist within the context of the sandbox

this difference is shown by these results:

|                                  | debug     | window.debug  | unsafeWindow.debug | this.debug    | globalThis.debug | self.debug    |
| -------------------------------- | --------- | ------------- | ------------------ | ------------- | ---------------- | ------------- |
| tampermonkey  unsafeWindow.debug | ok        | **undefined** | ok                 | **undefined** | **undefined**    | **undefined** |
| WebMonkey unsafeWindow.debug     | ok        | **ok**        | ok                 | **ok**        | **ok**           | **ok**        |

a more interesting test case to show the behavior of _WebMonkey_ might be:

```javascript
  unsafeWindow.debug = 'foo'
  console.log('unsafeWindow.debug = ' + unsafeWindow.debug) // 'foo'
  console.log('window.debug = ' + window.debug) // 'foo'

  window.debug = 'bar'
  console.log('unsafeWindow.debug = ' + unsafeWindow.debug) // 'foo'
  console.log('window.debug = ' + window.debug) // 'bar'
```

2. when a variable is added to the sandboxed `window` object, it cannot be referenced as a standalone in-scope variable
   * I would love to add this behavior, but I don't know if it's possible (using an [ES6 Proxy](https://github.com/warren-bank/Android-WebMonkey/blob/v04.08.00/android-studio-project/libs/webview-gm-lib/src/main/res/raw/js_closure_2_es6))

this difference is shown by these results:

|                                  | debug     | window.debug  |
| -------------------------------- | --------- | ------------- |
| tampermonkey  window.debug       | **ok**    | ok            |
| WebMonkey window.debug           | **error** | ok            |
| tampermonkey  this.debug         | **ok**    | ok            |
| WebMonkey this.debug             | **error** | ok            |
| tampermonkey  globalThis.debug   | **ok**    | ok            |
| WebMonkey globalThis.debug       | **error** | ok            |
| tampermonkey  self.debug         | **ok**    | ok            |
| WebMonkey self.debug             | **error** | ok            |

**Comment by warren-bank** [comment]
regarding (2).. dynamically injecting variables to the current scope.. I found this interesting..

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/with

* its a shame this `with` statement is deprecated
* although it warns that it could be removed from browsers at any time, I'm guessing (for compatibility) that won't be the case
* I'll need to run a few tests to make sure it works the way I think it does, but this seems like a good solution
  - ie: wrap the userscript by: `with(window) {...}`
  - ex: `with(window) {window.debug = 'ok';  console.log(typeof debug);}`

super quick test (in Firefox):
```javascript
{
  const my_window = {}
  with(my_window) {my_window.debug = 'ok';  console.log(typeof debug);}
  // output: string
}
```

**Comment by luomoxu** [comment]
I'm not very good at JavaScript
Maybe you can refer to the  chrome extension

**Comment by luomoxu** [comment]
Another question is about JavaScript code splicing
I guess you don’t really want to modify the relevant code of webview-gm
and then used other ways to extend it
But I have to say that the method of splicing JavaScript code in webview-gm is really not very elegant.
Then in order to be compatible with it, the derived code cannot be elegant
Extensive use of Java's ugly string concatenation will greatly reduce the readability of the code.
Maybe we can open another issue to discuss this issue

**Comment by warren-bank** [comment]
well..
* regarding (1): I like my implementation better
* regarding (2): I'll play around with adding `with`.. seems like an easy fix
* regarding looking at Tampermonkey's code..
  - you're probably right, that it might be helpful
  - there are major differences between running in a WebExtension, and running in a WebView..<br>but there might be some useful overlap
  - truthfully, I haven't even glanced at their code.. only their documentation
* regarding using string concatenation in the code..
  - I agree.. I very much dislike that too
  - it's how the original library was coded, and I haven't bothered to change it (yet)
  - I had considered moving the entire thing into a raw resource (as I have done with all of my static additions)
    * the only complication is that I would need to add placeholders for dynamic variables,<br>and essentially treat the file as a template
    * but.. it would make it much easier to read (and more importantly for me.. to edit)

**Comment by luomoxu** [comment]
I also think it would be better to use templates to solve
Using different templates to distinguish es5 es6 should be better than a large number of if
Although I am a newbie in JavaScript, but the editor keeps reminding me not to do this when I mix the syntax of es5 and es6.
I didn't find Tampermonkey's code either,Although there is a project address, there is no actual code
You can refer to this project https://github.com/violentmonkey/violentmonkey
or https://github.com/JingMatrix/ChromeXt (I haven't actually tested it yet, I will try it tomorrow and report back then)

**Comment by luomoxu** [comment]
> regarding (2).. dynamically injecting variables to the current scope.. I found this interesting..
> 
> [developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/with](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/with)
> 
> * its a shame this `with` statement is deprecated
> * although it warns that it could be removed from browsers at any time, I'm guessing (for compatibility) that won't be the case
> * I'll need to run a few tests to make sure it works the way I think it does, but this seems like a good solution
>   
>   * ie: wrap the userscript by: `with(window) {...}`
>   * ex: `with(window) {window.debug = 'ok';  console.log(typeof debug);}`
> 
> super quick test (in Firefox):
> 
> ```js
> {
>   const my_window = {}
>   with(my_window) {my_window.debug = 'ok';  console.log(typeof debug);}
>   // output: string
> }
> ```


I checked violentmonkey and Tampermonkey ,both of them use `with`
### violentmonkey 
```js
window.VMyz16gi44iv = function VMcc1sq64bbo(GM) {
    with (this) with (c) delete c, (
        (define, module, exports) =>
        {
            // ==UserScript==
// @name         debug
// @namespace    debug
// @version      0.0.1
// @description  debug
// @author       debug
// @match        https://*/*
// @grant        unsafeWindow
// ==/UserScript==
        console.log(this);
    })()
}
//# sourceURL=chrome-extension://jinjaccalgkegednnccohejagnlnfdag/debug.user.js#11
```
### Tampermonkey 
```js
window["__f__m40tx0dn.kxo"] = function () {
    with (this) {
        (async (u, {p, r, s}) => {
            try {
                r(u, s, [undefined, undefined, undefined, p.unsafeWindow, p.GM_info, p.GM]);
            } catch (e) {
                if (e.message && e.stack) {
                    console.error("ERROR: Execution of script 'debug' failed! " + e.message);
                    console.log(e.stack);
                } else {
                    console.error(e);
                }
            }
        })(async function (define, module, exports, unsafeWindow, GM_info, GM) {
// ==UserScript==
// @name         debug
// @namespace    debug
// @version      0.0.8
// @description  debug
// @author       debug
// @match        https://*/*
// @grant        unsafeWindow
// ==/UserScript==
            console.log(this);
        }, seed)
    }
//# sourceURL=chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=debug.user.js&id=e2717fee-5d02-4f84-a977-c3f084c61af9
}
```

**Comment by warren-bank** [comment]
wow.. thank you so much for doing such a deep dive to investigate the methodology that they each use. It makes me less wary to use `with` knowing (now) that everybody else does, as well.

I've started moving the concatenated strings to templates.
The GM API is done.. and now I'll do the same for the WM API.

After that's done.. I'll fix the bugs that you've discovered.
Again, I really appreciate your help!

**Comment by warren-bank** [comment]
[v04.09.00](https://github.com/warren-bank/Android-WebMonkey/releases/tag/v04.09.00) includes all of the updates that we've discussed:
* replace string concatenation used to assembly the JS API with file templates (1 for GM, and 1 for WM)
* fix ES6 Proxy `set()` return value
* wrap `with(window)` around userscript, so variables added to the sandbox are automatically injected into the scope
  - add a new [test userscript](https://github.com/warren-bank/Android-WebMonkey/raw/v04.09.00/tests/0021b-closure-sandbox.user.js) to reproduce your earlier results,<br>and (by comparison) show the effect of these recent changes
  - note: this test runs in 'strict' mode.. and no ES6 Proxy errors
  - <details>
      <summary>output:</summary>

      <table border="1px" style="white-space: nowrap;"><tr><th></th><th>foo</th><th>unsafeWindow.foo</th><th>window.foo</th><th>self.foo</th><th>this.foo</th><th>globalThis.foo</th></tr><tr><td>var foo = 1</td><td>number</td><td>undefined</td><td>undefined</td><td>undefined</td><td>undefined</td><td>undefined</td></tr><tr><td>unsafeWindow.foo = 1</td><td>number</td><td>number</td><td>number</td><td>number</td><td>number</td><td>number</td></tr><tr><td>window.foo = 1</td><td>number</td><td>undefined</td><td>number</td><td>number</td><td>number</td><td>number</td></tr><tr><td>self.foo = 1</td><td>number</td><td>undefined</td><td>number</td><td>number</td><td>number</td><td>number</td></tr><tr><td>this.foo = 1</td><td>number</td><td>undefined</td><td>number</td><td>number</td><td>number</td><td>number</td></tr><tr><td>globalThis.foo = 1</td><td>number</td><td>undefined</td><td>number</td><td>number</td><td>number</td><td>number</td></tr></table>
    </details>
