### ISSUE TITLE
When "use strict" , windowProxyHander set will throw exception

### ISSUE THREAD

**Issue by luomoxu** [warren-bank/Android-WebMonkey#19]
In line 
https://github.com/warren-bank/Android-WebMonkey/blob/29d9f64e6e94273529cf657486e20d1146fce5bc/android-studio-project/libs/webview-gm-lib/src/main/res/raw/js_closure_2_es6#L84

set must return true or false

maybe `use strict`  can be the default in test case

**Comment by warren-bank** [comment]
nice catch..
apparently, this method should [return](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy/Proxy/set#return_value) a boolean to indicate success/failure
thanks!
