### ISSUE TITLE
UserScript run twice

### ISSUE THREAD

**Issue by luomoxu** [warren-bank/Android-WebMonkey#21]
Test on [v04.09.02](https://github.com/warren-bank/Android-WebMonkey/releases/tag/v04.09.02)
UserScript code
```
// ==UserScript==
// @name         debug
// @namespace    debug
// @version      0.0.1
// @description  debug
// @author       debug
// @match        https://*/*
// @grant        unsafeWindow
// ==/UserScript==
console.log(JSON.stringify(GM_info));
```
The webview  onPageFinished function call twice on site  https://netflav5.com/browse (NSFW)
This should not be an isolated case. Many websites may have this problem.

**Comment by warren-bank** [comment]
you're not wrong..
I've observed this behavior in the past when I've run various tests..
from memory, I want to say that it happens on the google.com homepage.

quick research into issue..

1. [issue on stackoverflow](https://stackoverflow.com/questions/18282892/android-webview-onpagefinished-called-twice)
   * [interesting approach](https://stackoverflow.com/a/60328762) using [`webview.getProgress`](https://developer.android.com/reference/android/webkit/WebView#getProgress())

**Comment by warren-bank** [comment]
<details>
  <summary><h4>WebView code trace:</h4></summary>

  https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/webkit/WebView.java#1338
  * "WebView.getProgress" is delegated to "mProvider.getProgress"

  https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/webkit/WebView.java#2414
  * "mProvider" is an instance of "WebViewProvider"

  https://android.googlesource.com/platform/frameworks/base/+/refs/heads/main/core/java/android/webkit/WebViewProvider.java
  * "WebViewProvider" is an interface

  https://android.googlesource.com/platform/frameworks/webview/+/4dcabae/chromium/java/com/android/webview/chromium/WebViewChromium.java#70
  * "WebViewChromium" implements "WebViewProvider"

  https://android.googlesource.com/platform/frameworks/webview/+/4dcabae/chromium/java/com/android/webview/chromium/WebViewChromium.java#411
  * "mProvider.getProgress" delegates to "mAwContents.getMostRecentProgress"

  https://android.googlesource.com/platform/frameworks/webview/+/4dcabae/chromium/java/com/android/webview/chromium/WebViewChromium.java#53
  * package: "org.chromium.android_webview.AwContents"

  https://chromium.googlesource.com/chromium/src.git/+/refs/heads/main/android_webview/java/src/org/chromium/android_webview/AwContents.java#2199
  * "mAwContents.getMostRecentProgress"
    - returns 100 when "mWebContents.isLoading()" is false
    - otherwise, delegates to "mWebContents.getLoadProgress"

  https://chromium.googlesource.com/chromium/src.git/+/refs/heads/main/android_webview/java/src/org/chromium/android_webview/AwContents.java#122
  * package: "org.chromium.content_public.browser.WebContents"

  https://chromium.googlesource.com/chromium/src.git/+/refs/heads/main/content/public/android/java/src/org/chromium/content_public/browser/WebContents.java
  * "WebContents" is an interface

  https://chromium.googlesource.com/chromium/src.git/+/refs/heads/main/content/public/android/java/src/org/chromium/content/browser/webcontents/WebContentsImpl.java#84
  * "WebContentsImpl" implements "WebContents"

  https://chromium.googlesource.com/chromium/src.git/+/refs/heads/main/content/public/android/java/src/org/chromium/content/browser/webcontents/WebContentsImpl.java#533
  * "mWebContents.isLoading()" delegates to "WebContentsImplJni.get().isLoading"<br>..native code

  https://chromium.googlesource.com/chromium/src.git/+/refs/heads/main/content/public/android/java/src/org/chromium/content/browser/webcontents/WebContentsImpl.java#797
  * "mWebContents.getLoadProgress" delegates to "WebContentsImplJni.get().getLoadProgress"<br>..native code
</details>

**Comment by warren-bank** [comment]
#### related bug reports

1. [Google: 36983315](https://issuetracker.google.com/issues/36983315)
   * reported when Android 4.4 was released
     - the assertion is that the culprit has to do with pages that contain iframes..<br>events from nested windows are bubbling up
   * [this patch](https://codereview.chromium.org/68763012/) only involves the javascript `history` API
   * most recent comment: 2 months ago
     - to confirm that this issue still exists in Android 14 (API 34)

**Comment by warren-bank** [comment]
<details>
  <summary><h4>WebMonkey code trace:</h4></summary>

  https://github.com/warren-bank/Android-WebMonkey/blob/v04.09.02/android-studio-project/libs/webview-gm-lib/src/main/java/at/pardus/android/webview/gm/run/WebViewClientGm.java#L91-L101
  * method: "runMatchingScripts"
    - input parameter: `String url`
    - input parameter: `boolean pageFinished`

https://github.com/warren-bank/Android-WebMonkey/blob/v04.09.02/android-studio-project/libs/webview-gm-lib/src/main/java/at/pardus/android/webview/gm/run/WebViewClientGm.java#L130
  * method: "onPageStarted"
    - calls: `runMatchingScripts(url, false)`

https://github.com/warren-bank/Android-WebMonkey/blob/v04.09.02/android-studio-project/libs/webview-gm-lib/src/main/java/at/pardus/android/webview/gm/run/WebViewClientGm.java#L135
  * method: "onPageFinished"
    - calls: `runMatchingScripts(url, true)`
</details>

**Comment by warren-bank** [comment]
I wrote [a little utility app](https://github.com/warren-bank/Android-WebViewClientObserver) last night to be able to easily see the events being processed by the [`WebViewClient`](https://developer.android.com/reference/android/webkit/WebViewClient).. as I visit different websites.

It quickly becomes apparent that the "progress" value doesn't provide an easy fix. For example, on "youtube.com", `onPageFinished` is called twice.. and progress is `100` for both calls.

As much as I'd like to prevent this from happening.. the fix needs to happen at the `WebView` level. Anything that I could try in userspace would be hacky and prone to error.

**Comment by luomoxu** [comment]
I would like to provide an idea. If we always put the `runMatchingScripts` at the `onPageStarted`, and the timing of `document-end` is judged through `window.onload`, we should be able to solve the problem of embedded iframes.

**Comment by warren-bank** [comment]
[v04.10.00](https://github.com/warren-bank/Android-WebMonkey/releases/tag/v04.10.00) adds a Setting that gives the ability to choose which methodology is used to invoke scripts having `@run-at document-end`. The new option `document: DOMContentLoaded` is now the default, which adds the script when the `WebViewClient.onPageStarted` event is called, but uses javascript to defer its execution until the proper time.

I was initially hesitant to do this, because the issue and discussion surrounding it includes several comments that observe `WebViewClient.onPageStarted` being called more than once per page load. If these reports are correct, then this new methodology will also cause userscripts to run more than once. However, in my (admittedly very limited) testing of various websites using my new [utility app](https://github.com/warren-bank/Android-WebViewClientObserver).. multiple `onPageFinished` events are very common.. and I have yet to see an instance of multiple `onPageStarted` events. So.. anecdotally.. it appears to be an improvement.

note:
* in _WebMonkey_.. both `@run-at document-end` and `@run-at document-idle` are effectively the same.

room for improvement:
* when the option `document: DOMContentLoaded` is selected..
  - I could wire `@run-at document-idle` to execute when:<br>[`window.addEventListener('load', userscript)`](https://developer.mozilla.org/en-US/docs/Web/API/Window/load_event) is called

**Comment by luomoxu** [comment]
> [v04.10.00](https://github.com/warren-bank/Android-WebMonkey/releases/tag/v04.10.00) adds a Setting that gives the ability to choose which methodology is used to invoke scripts having `@run-at document-end`. The new option `document: DOMContentLoaded` is now the default, which adds the script when the `WebViewClient.onPageStarted` event is called, but uses javascript to defer its execution until the proper time.
> 
> I was initially hesitant to do this, because the issue and discussion surrounding it includes several comments that observe `WebViewClient.onPageStarted` being called more than once per page load. If these reports are correct, then this new methodology will also cause userscripts to run more than once. However, in my (admittedly very limited) testing of various websites using my new [utility app](https://github.com/warren-bank/Android-WebViewClientObserver).. multiple `onPageFinished` events are very common.. and I have yet to see an instance of multiple `onPageStarted` events. So.. anecdotally.. it appears to be an improvement.
> 
> note:
> 
> * in _WebMonkey_.. both `@run-at document-end` and `@run-at document-idle` are effectively the same.
> 
> room for improvement:
> 
> * when the option `document: DOMContentLoaded` is selected..
>   
>   * I could wire `@run-at document-idle` to execute when:[`window.addEventListener('load', userscript)`](https://developer.mozilla.org/en-US/docs/Web/API/Window/load_event) is called

I tested the latest version
May be the WebViewGM_ON_PAGE_FINISHED should include `@require` javascript

**Comment by warren-bank** [comment]
it does..
all of the `@require` scripts are prepended to the userscript..
then wrapped in a function..
that gets called when the document is ready.

proof..

```javascript
// ==UserScript==
// @name         debug
// @namespace    debug
// @version      0.0.1
// @match        *://*/*
// @require      https://cdn.jsdelivr.net/gh/warren-bank/js-url/es5-browser/jsURL.js
// @run-at       document-end
// ==/UserScript==

try {
  const secret     = '12345'
  const url        = window.location.href
  const userscript = window.WebViewWM.getUserscriptJS(secret, url)

  document.body.innerHTML = '<' + 'pre>' + userscript + '<' + '/pre>'
}
catch(e) {
  window.alert(e.message)
}
```

requirement:
* _Settings_ &gt; _Shared Secret_ = `12345`

**Comment by warren-bank** [comment]
farther proof..
by referencing the dependency directly:

```javascript
// ==UserScript==
// @name         debug
// @namespace    debug
// @version      0.0.1
// @match        *://*/*
// @require      https://cdn.jsdelivr.net/gh/warren-bank/js-url/es5-browser/jsURL.js
// @run-at       document-end
// ==/UserScript==

try {
  window.alert('typeof window.jsURL.parse = ' + (typeof window.jsURL.parse))
}
catch(e) {
  window.alert(e.message)
}
```

**Comment by luomoxu** [comment]
I try this userscript
```
// ==UserScript==
// @name         debug
// @namespace    debug
// @version      0.0.1
// @description  debug
// @author       debug
// @match        http*://*/*
// @require      https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.slim.min.js
// @grant        unsafeWindow
// ==/UserScript==
console.log(JSON.stringify(GM_info));
```
I found in Chrome Remote DevTools 
```
            (function() {
                var WebViewGM_ON_PAGE_FINISHED = function() {
                    // ==UserScript==
                    // @name         debug
                    // @namespace    debug
                    // @version      0.0.1
                    // @description  debug
                    // @author       debug
                    // @match        http*://*/*
                    // @require      https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.slim.min.js
                    // @grant        unsafeWindow
                    // ==/UserScript==
                    console.log(JSON.stringify(GM_info));
                };

                if (document.readyState === 'loading') {
                    document.addEventListener('DOMContentLoaded', WebViewGM_ON_PAGE_FINISHED);
                } else {
                    WebViewGM_ON_PAGE_FINISHED();
                }
            }
            )();
```
`@require` is out of WebViewGM_ON_PAGE_FINISHED

**Comment by warren-bank** [comment]
try to use `jQuery`.. see what happens.

**Comment by luomoxu** [comment]
> try to use `jQuery`.. see what happens.

jquery init error

**Comment by warren-bank** [comment]
it works for me;
I can't reproduce your error..

```javascript
// ==UserScript==
// @name         debug
// @namespace    debug
// @version      0.0.1
// @match        *://*/*
// @require      https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.slim.min.js
// @run-at       document-end
// ==/UserScript==

try {
  window.alert('typeof window.jQuery = ' + (typeof window.jQuery))
  window.alert('document.body.tagName = ' + window.jQuery('body').get(0).tagName)
}
catch(e) {
  window.alert(e.message)
}
```

**Comment by luomoxu** [comment]
> ```js
> // @run-at       document-end
> ```
https://github.com/jquery/jquery/issues/3333
I think if the script is set to document-end, all of code is run at document-end,include require lib

**Comment by warren-bank** [comment]
yep.. same as before

that doesn't change.. whether the userscript is triggered by `WebViewClient.onPageFinished` or `DOMContentLoaded`

- - - -

regarding the issue that you linked to..
which pertains to:
> undefined `document`

can you provide a userscript example that produces this error?

**Comment by luomoxu** [comment]
> I try this userscript
> 
> ```
> // ==UserScript==
> // @name         debug
> // @namespace    debug
> // @version      0.0.1
> // @description  debug
> // @author       debug
> // @match        http*://*/*
> // @require      https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.slim.min.js
> // @grant        unsafeWindow
> // ==/UserScript==
> console.log(JSON.stringify(GM_info));
> ```
> 
> I found in Chrome Remote DevTools
> 
> ```
>             (function() {
>                 var WebViewGM_ON_PAGE_FINISHED = function() {
>                     // ==UserScript==
>                     // @name         debug
>                     // @namespace    debug
>                     // @version      0.0.1
>                     // @description  debug
>                     // @author       debug
>                     // @match        http*://*/*
>                     // @require      https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.slim.min.js
>                     // @grant        unsafeWindow
>                     // ==/UserScript==
>                     console.log(JSON.stringify(GM_info));
>                 };
> 
>                 if (document.readyState === 'loading') {
>                     document.addEventListener('DOMContentLoaded', WebViewGM_ON_PAGE_FINISHED);
>                 } else {
>                     WebViewGM_ON_PAGE_FINISHED();
>                 }
>             }
>             )();
> ```
> 
> `@require` is out of WebViewGM_ON_PAGE_FINISHED

This one will throw error for me

**Comment by warren-bank** [comment]
observations:
1. you're loading `jQuery` as a dependency, but not using it
2. I've already shown that loading `jQuery` as a dependency works.. and the library is available
3. all you're doing is logging: `GM_info`
   - I'll test that this variable is still defined.. brb

**Comment by warren-bank** [comment]
test case:

```javascript
// ==UserScript==
// @name         debug
// @namespace    debug
// @version      0.0.1
// @match        *://*/*
// @require      https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.slim.min.js
// @run-at       document-end
// ==/UserScript==

try {
  window.alert('typeof window.jQuery = ' + (typeof window.jQuery))
  window.alert('document.body.tagName = ' + window.jQuery('body').get(0).tagName)

  document.body.innerHTML = '<' + 'pre>' + JSON.stringify(GM_info, null, 2) + '<' + '/pre>'
}
catch(e) {
  window.alert(e.message)
}
```

results:
1. works as expected
   - `jQuery` works
   - `GM_info` is defined
2. though I did notice that:
   - `GM_info.script.requires === undefined`
   - I'm guessing this field should exist.. will need to double check the spec to confirm

update:
* surprisingly.. the answer is.. _no_
  - [GM_info](https://www.tampermonkey.net/documentation.php?locale=en#api:GM_info) doesn't contain any field that lists the script's dependencies

**Comment by luomoxu** [comment]
The important thing is not jquery
debug.lib.js
```js
console.log("require",document.readyState);
```
userSciript
```js
// ==UserScript==
// @name         debug
// @namespace    debug
// @version      0.0.1
// @description  debug
// @author       debug
// @match        *://*/*
// @require      debug.lib.js
// ==/UserScript==
console.log("main",document.readyState);
```
output
```
require loading
main interactive
```

**Comment by warren-bank** [comment]
shoot.. you're right!

although I didn't see any negative effect for using the current release..
you're right, that the closure isn't the outer-most function, as I thought it would be..
instead, it's more like:
* load API
* load sandbox
* load required dependencies
* add userscript in event listener callback

so..
* even though all of the earlier stuff doesn't occur from within the event listener callback, it is all in scope when the userscript is executed
* if any of the earlier stuff needs to touch the DOM.. it will break
  - for example: requiring a script that calls `document.body.appendChild(document.createElement('div'))`

that being said..
* it would be better if everything occurs in the event listener callback (as I though was the case)..
* I'll dig into it.. and find the touch point for making this change
* thanks for pointing it! you're a big help

**Comment by luomoxu** [comment]
I think you will fall into the code structure trap of webview-gm-lib again 😂

**Comment by warren-bank** [comment]
[v04.10.04](https://github.com/warren-bank/Android-WebMonkey/releases/tag/v04.10.04) reorganizes the closures.. the way that I had originally intended. Thanks again.. for catching that the closures were nested improperly.. that was an obscure detail to notice.. great job :)

**Comment by warren-bank** [comment]
quick update..

I had [mentioned earlier](#issuecomment-2557175591) that there is..

> room for improvement:
> * when the option `document: DOMContentLoaded` is selected..
>   - I could wire `@run-at document-idle` to execute when:<br>[`window.addEventListener('load', userscript)`](https://developer.mozilla.org/en-US/docs/Web/API/Window/load_event) is called

[v04.11.00](https://github.com/warren-bank/Android-WebMonkey/releases/tag/v04.11.00) adds that functionality

**Comment by luomoxu** [comment]
I noticed that many of your projects are related to video playback on TV. 
My research on this project is also related. 
I would like to introduce you to a popular solution in China.
There is an open-source video playback app that does not contain any processing logic for video sources.
It can load DEX files and execute them to obtain video source information for playback. 
Currently, a mainstream approach is to run custom Java code logic to scrape or call third-party APIs, and then convert it into the output format supported by this app.
It also supports running a Python engine in a Java environment to execute Python files. 
Additionally, there is a JavaScript engine (QuickJS) that can run JavaScript files in a Java environment. 
Recently, I have been working on a method that utilizes WebView to run user scripts, which offers better flexibility and resistance to anti-scraping measures. 

https://github.com/FongMi/TV
https://github.com/FongMi/CatVodSpider

You can download the relevant APK files here, but the UI is primarily in Chinese, so it might be a bit challenging to use for the first time.
https://github.com/FongMi/Release/tree/fongmi/apk/release

First time you can try use leanback-python-armeabi_v7a.apk on tv devices

Let me briefly introduce how to switch to English and how to set it up

open `设置`-`个性设置`-`语言设置`-`英文` change language to English

open `设置`-`Vod`

In the input box on the right side of the pop-up page with the QR code, enter `http://www.饭太硬.com/tv/` This is just an example. Click OK and then return to the main interface, and you can give it a try.


If you need any further assistance, feel free to ask!

If you're interested, I can share my solution with you.

**Comment by warren-bank** [comment]
Thanks for the info about this app.. I took a quick peek.
Since I couldn't find any documentation in English, I figured I'd browse its code.

Please correct me if I'm wrong, but my understanding is that..
* each of [these spiders](https://github.com/FongMi/CatVodSpider/tree/main/app/src/main/java/com/github/catvod/spider) is site-specific
  - presents a custom UI to browse the list of available video content
  - downloads and parses various bits and bobs..<br>until it can extract a link for the desired video
* in my personal experience, maintaining these types of crawlers is a nightmare..
  - as you noted, I've written several in the form of [standalone userscripts](https://github.com/warren-bank?tab=repositories&q=crx-)
  - some (not all) require frequent updates, which I tend not to do
  - personal preference, but I feel that Javascript is much better suited to this task than Java
* the overall goal of this project seems very similar to [youtube-dl](https://github.com/ytdl-org/youtube-dl)
  - in the sense that they maintain a ridiculously vast number of [website extractors](https://github.com/ytdl-org/youtube-dl/tree/master/youtube_dl/extractor)
  - all written in Python

**Comment by warren-bank** [comment]
An idea for a project that would be absolutely amazing..
would be to build an Android app that provides a front-end for _youtube-dl_..
to be able to browse a simple (and normalized) list of videos for all of the sites that it supports..
and then when any video is selected, start an Intent to play the video URL (w/ subtitles, DRM, Referer, etc) in an external video player app.

**Comment by luomoxu** [comment]
Your understanding is mostly correct.

> would be to build an Android app that provides a front-end for *youtube-dl*..

This analogy is very appropriate.

I would like to add a few points: it comes with a complete built-in player, including Exo, IJK, VLC (on TV), and MPV (on mobile), so you can play videos without using an external player.

In the past ,I used `Web Video Caster` on mobile deivces  along with `AirReceiver` + `MX Player` on  TV to play videos from the web

but this setup is too complicated for people who are not familiar with electronic products. with the app , I can operate everything directly on the TV using the remote control.
> personal preference, but I feel that Javascript is much better suited to this task than Java

I think so too. on the web, JavaScript is undoubtedly the king, which is why I want to use WebView + User Script to accomplish this.
In fact, there are already multiple implementation solutions in various languages available.

**Comment by luomoxu** [comment]
A small gift for you,try to import this config file
`https://github.com/CatVodSpider-GM/gift/raw/refs/heads/main/index.json`

**Comment by warren-bank** [comment]
wow.. that's great!

now I kinda get it..
that the config file can specify a [custom .jar library](https://github.com/CatVodSpider-GM/gift/blob/main/Spiders-Lib/GM.jar) that is used for the specified "sites"..
I'm going to guess that the main class in each .jar must extend the [abstract `Spider` class](https://github.com/FongMi/CatVodSpider/blob/main/app/src/main/java/com/github/catvod/crawler/Spider.java)..
is that correct? ..if so, then it would make sense how the pieces fit together.

so the magic is happening in your `GM.jar` library..
is its source code available? ..I'd be curious to see the particulars.

**Comment by luomoxu** [comment]
I Invited you
Because the code was written quite crudely, it was not open source now.

**Comment by warren-bank** [comment]
thanks for the invite.. I've already accepted, and I'm reading the code now :)

**Comment by warren-bank** [comment]
I hope, for your sake, that you're going to have help to maintain the userscripts for the sites that you choose to support.
Development is hard, but long term maintenance is hell.

My comment last night got me thinking..
based on the fact that _youtube-dl_ and its various forks are so well maintained..
and that I'm lazy..
the idea popped into my head for a userscript that I'd like to try to develop..
one that includes a Python interpreter as a WASM resource..
and loads _youtube-dl_ as a library..
and processes the current page.

considerations:
* light-weight by default
  - show a button on pages that match the userscript URL regex
  - only after the button is clicked should the WASM be loaded and executed,<br>which would be CPU/RAM intensive
* I'm not sure if this is even possible,<br>but I've seen it done for other Python libraries
  - ex: [PyMuPDF](https://github.com/pymupdf/PyMuPDF) web console: [code](https://github.com/warren-bank/single-page-apps/tree/gh-pages/pymupdf-web-console) and [demo](https://warren-bank.github.io/single-page-apps/pymupdf-web-console/index.html)
* this design should be quite similar to my [Youtube transcoder userscript](https://github.com/warren-bank/crx-Youtube-transcoder),<br>which includes [ffmpeg.wasm](https://github.com/ffmpegwasm/ffmpeg.wasm) as a WASM resource

**Comment by luomoxu** [comment]
A bold idea.
I would like to understand some details about what you plan to develop:
An Android application,
An Android library,
A cross-platform script execution engine,
Or something else?

**Comment by warren-bank** [comment]
well.. if I'm able to get it working, then it would simply be a userscript that's active on all pages for which `youtube-dl` has an "extractor".

and it could run in any userscript manager.. WebMonkey, TamperMonkey, ViolentMonkey, etc.

well.. with the caveat that TamperMonkey on Chrome currently has [an issue](https://github.com/Tampermonkey/tampermonkey/issues/2236) that prevents scripts containing large resources from running.

**Comment by warren-bank** [comment]
As a first baby step, I'm trying to get [`yt-dlp`](https://github.com/yt-dlp/yt-dlp) to work in a standalone webpage with the WASM Python interpreter.
It's a fork of `youtube-dl`.. with more features, better maintenance, and (most importanly) their workflow publishes a .whl with every release.

[Here](https://warren-bank.github.io/single-page-apps/yt-dlp-web-console/index.html) is my work-in-progress.
The library is loaded and its methods can be called,
but I'm getting `TransportError('timed out')` when it tries to download a Youtube webpage to inspect.

I'll need to poke around the libraries source code to see what HTTP client is being used..
and I think I may ask for help in their issues, since they know their library best (and I rarely touch Python).

**Comment by luomoxu** [comment]
I know more about wasm
I probably know what you want to do
Another question is what problem do you want to help users solve? Get the download address? Or directly download the complete video file to the local

**Comment by luomoxu** [comment]
> As a first baby step, I'm trying to get [`yt-dlp`](https://github.com/yt-dlp/yt-dlp) to work in a standalone webpage with the WASM Python interpreter.作为第一步，我尝试让[`yt-dlp`](https://github.com/yt-dlp/yt-dlp)使用 WASM Python 解释器在独立网页中工作。 It's a fork of `youtube-dl`.. with more features, better maintenance, and (most importanly) their workflow publishes a .whl with every release.它是`youtube-dl`的一个分支。具有更多功能、更好的维护，并且（最重要的是）他们的工作流程在每个版本中都会发布 .whl。
> 
> [Here](https://warren-bank.github.io/single-page-apps/yt-dlp-web-console/index.html) is my work-in-progress.[这](https://warren-bank.github.io/single-page-apps/yt-dlp-web-console/index.html)是我正在进行的工作。 The library is loaded and its methods can be called,库已加载并且可以调用其方法， but I'm getting `TransportError('timed out')` when it tries to download a Youtube webpage to inspect.但我收到`TransportError('timed out')`当它尝试下载 Youtube 网页进行检查时。
> 
> I'll need to poke around the libraries source code to see what HTTP client is being used..我需要浏览库源代码来查看正在使用的 HTTP 客户端。 and I think I may ask for help in their issues, since they know their library best (and I rarely touch Python).我想我可能会在他们的问题上寻求帮助，因为他们最了解他们的库（而且我很少接触Python）。

This one maybe help you https://github.com/vasilev/HTTP-request-from-inside-WASM#python
