### ISSUE TITLE
use native Android System WebView 

### ISSUE THREAD

**Issue by Pantyhose-X** [warren-bank/Android-WebMonkey#4]
based [Chromium](https://www.chromium.org/Home) Delete browser kernel

**Comment by warren-bank** [comment]
that's exactly what this app (and its underlying _WebView GM_ library) already does..

of course, how WebView is implemented on any individual device is dependent on the version of Android that it is running; to summarize:
* Android &lt;= 4.4
  - WebView is baked into firmware, cannot be updated
* Android &gt;= 5.0 and &lt; 7.0
  - uses Android System WebView, which is a standalone app that can be updated from Playstore
* Android &gt;= 7.0
  - can continue to use Android System WebView as a fallback, but uses the Chrome app (if installed and enabled)

**Comment by Pantyhose-X** [comment]
> that's exactly what this app (and its underlying _WebView GM_ library) already does..
> 
> of course, how WebView is implemented on any individual device is dependent on the version of Android that it is running;
> to summarize:
> 
> * Android < 5.0
>   
>   * WebView is baked into firmware, cannot be updated
> * Android >= 5.0 and < 7.0
>   
>   * uses Android System WebView, which is a standalone app that can be updated from Playstore
> * Android >= 7.0
>   
>   * can continue to use Android System WebView as a fallback, but uses the Chrome app (if installed and enabled)

UI   based [Chromium](https://www.chromium.org/Home) Delete browser kernel
