### ISSUE TITLE
Error cleartext traffic is not permitted

### ISSUE THREAD

**Issue by PurpleCodingWizard** [warren-bank/Android-WebMonkey#5]
I Typed ddg.co in the address bar, and the app tried http://ddg.co but was blocked.

Newer versions of android(8/9 and higher)  block cleartext traffic by default. An exception to allow http would be great.

A resource which could help.
https://stackoverflow.com/questions/45940861/android-8-cleartext-http-traffic-not-permitted

**Comment by warren-bank** [comment]
Thanks for letting me know; I wasn't aware of that policy change. I'll push updates to all of my Android apps that use network connections, including WebMonkey.. within a day or so.

**Comment by warren-bank** [comment]
Sorry for the delay; I was in the weeds on a different project.

Anyway, please let me know whether [v1.0.19](https://github.com/warren-bank/Android-WebMonkey/releases/tag/v01.00.19) solves this issue. Thanks.

**Comment by PurpleCodingWizard** [comment]
Yeah, its working fine. Cheers 🍻
